/**
 * All 30 道具, one per `item/` ID in `docs/ASSETS.md`:
 * 8 丹药 + 8 材料 + 4 法宝 + 4 法衣 + 3 饰品 + 3 灵宠.
 */

import { indexById } from '../core/util.js';
import { ZERO_STAT_BONUS, type StatBonus } from '../domain/stats.js';
import {
  ItemSchema,
  type EquipmentItem,
  type Item,
  type MaterialItem,
  type PillItem,
} from '../domain/item.js';

const bonus = (p: Partial<StatBonus>): StatBonus => ({ ...ZERO_STAT_BONUS, ...p });

const PILLS: PillItem[] = [
  {
    id: 'pill-qi',
    kind: 'pill',
    name: '聚气丹',
    description: '最寻常的入门丹药，服后灵气汇聚，修炼速度提升 30%，持续一个时辰。',
    art: 'item/pill-qi',
    grade: 'mortal',
    stackable: true,
    sellPrice: 25,
    buyPrice: 60,
    effect: { type: 'cultivation_buff', bonus: 0.3, durationSec: 3600 },
  },
  {
    id: 'pill-foundation',
    kind: 'pill',
    name: '筑基丹',
    description: '固本培元之丹，直接增益一笔可观修为。筑基期修士常备。',
    art: 'item/pill-foundation',
    grade: 'spirit',
    stackable: true,
    sellPrice: 180,
    buyPrice: 450,
    effect: { type: 'instant_exp', exp: 2400 },
  },
  {
    id: 'pill-breakthrough',
    kind: 'pill',
    name: '破境丹',
    description: '冲关破境之至宝。每服一枚，突破成功率 +15%，一次最多四枚。',
    art: 'item/pill-breakthrough',
    grade: 'immortal',
    stackable: true,
    sellPrice: 600,
    buyPrice: 1500,
    effect: { type: 'breakthrough_aid', bonus: 0.15 },
  },
  {
    id: 'pill-heal',
    kind: 'pill',
    name: '回春丹',
    description: '战后疗伤之用，立复六成气血。',
    art: 'item/pill-heal',
    grade: 'mortal',
    stackable: true,
    sellPrice: 40,
    buyPrice: 100,
    effect: { type: 'heal', healPercent: 0.6 },
  },
  {
    id: 'pill-spirit',
    kind: 'pill',
    name: '凝神丹',
    description: '凝神静气，两刻钟内命中与暴击大增，斗法前服用最佳。',
    art: 'item/pill-spirit',
    grade: 'spirit',
    stackable: true,
    sellPrice: 120,
    buyPrice: 300,
    effect: {
      type: 'stat_buff',
      stats: { crit: 0.08, acc: 0.06 },
      durationSec: 1800,
    },
  },
  {
    id: 'pill-power',
    kind: 'pill',
    name: '龙力丹',
    description: '龙血炼就，服后攻防暴涨，半个时辰内战力非凡。',
    art: 'item/pill-power',
    grade: 'immortal',
    stackable: true,
    sellPrice: 320,
    buyPrice: 800,
    effect: {
      type: 'stat_buff',
      stats: { atk: 0.25, def: 0.2 },
      durationSec: 1800,
    },
  },
  {
    id: 'pill-golden-core',
    kind: 'pill',
    name: '金元丹',
    description: '结丹之资，蕴含浑厚修为，金丹期以上修士方能承受。',
    art: 'item/pill-golden-core',
    grade: 'immortal',
    stackable: true,
    sellPrice: 1400,
    buyPrice: 3500,
    effect: { type: 'instant_exp', exp: 48000 },
  },
  {
    id: 'pill-enlightenment',
    kind: 'pill',
    name: '悟道丹',
    description: '传说中的顿悟之丹，修炼速度提升一倍，持续四个时辰。',
    art: 'item/pill-enlightenment',
    grade: 'saint',
    stackable: true,
    sellPrice: 2800,
    buyPrice: 7000,
    effect: { type: 'cultivation_buff', bonus: 1.0, durationSec: 14400 },
  },
];

const MATERIALS: MaterialItem[] = [
  {
    id: 'mat-spirit-herb',
    kind: 'material',
    name: '灵草',
    description: '山野常见的灵植，炼制低阶丹药的主料。',
    art: 'item/mat-spirit-herb',
    grade: 'mortal',
    stackable: true,
    sellPrice: 8,
    buyPrice: 20,
  },
  {
    id: 'mat-iron-essence',
    kind: 'material',
    name: '玄铁精',
    description: '铁中之精，铸炼法宝的根基之材。',
    art: 'item/mat-iron-essence',
    grade: 'spirit',
    stackable: true,
    sellPrice: 45,
    buyPrice: 120,
  },
  {
    id: 'mat-beast-core',
    kind: 'material',
    name: '妖丹',
    description: '妖兽体内凝结的灵核，蕴含精纯妖力。',
    art: 'item/mat-beast-core',
    grade: 'spirit',
    stackable: true,
    sellPrice: 60,
    buyPrice: 160,
  },
  {
    id: 'mat-spirit-stone',
    kind: 'material',
    name: '灵石',
    description: '修真界通行之物。此处所列为成块的粗胚，可兑作散碎灵石。',
    art: 'item/mat-spirit-stone',
    grade: 'mortal',
    stackable: true,
    sellPrice: 100,
    buyPrice: null,
  },
  {
    id: 'mat-jade',
    kind: 'material',
    name: '灵玉',
    description: '温润含灵，制饰品之上选。',
    art: 'item/mat-jade',
    grade: 'immortal',
    stackable: true,
    sellPrice: 150,
    buyPrice: 400,
  },
  {
    id: 'mat-soul-crystal',
    kind: 'material',
    name: '魂晶',
    description: '幽冥谷特产，凝聚亡魂精粹，寒气逼人。',
    art: 'item/mat-soul-crystal',
    grade: 'immortal',
    stackable: true,
    sellPrice: 260,
    buyPrice: 700,
  },
  {
    id: 'mat-cloud-silk',
    kind: 'material',
    name: '云纹丝',
    description: '云中蛛所吐之丝，轻若无物，织法衣不可或缺。',
    art: 'item/mat-cloud-silk',
    grade: 'immortal',
    stackable: true,
    sellPrice: 220,
    buyPrice: 600,
  },
  {
    id: 'mat-thunder-wood',
    kind: 'material',
    name: '雷击木',
    description: '历天雷而不焚的古木，天生克制邪祟。',
    art: 'item/mat-thunder-wood',
    grade: 'saint',
    stackable: true,
    sellPrice: 800,
    buyPrice: 2200,
  },
];

const EQUIPMENT: EquipmentItem[] = [
  // ------------------------------------------------------------- 法宝 treasure
  {
    id: 'treasure-sword',
    kind: 'equipment',
    name: '青锋剑',
    description: '青云宗弟子入门佩剑，锋锐轻捷。',
    art: 'item/treasure-sword',
    grade: 'mortal',
    stackable: false,
    slot: 'treasure',
    requiredStage: 0,
    sellPrice: 50,
    buyPrice: 150,
    flat: bonus({ atk: 6 }),
    percent: bonus({ atk: 0.08, crit: 0.01 }),
  },
  {
    id: 'treasure-bell',
    kind: 'equipment',
    name: '镇魂铃',
    description: '铃响则魂摇，攻守兼备的灵阶法宝。',
    art: 'item/treasure-bell',
    grade: 'spirit',
    stackable: false,
    slot: 'treasure',
    requiredStage: 6,
    sellPrice: 400,
    buyPrice: 1100,
    flat: bonus({ atk: 14, def: 6 }),
    percent: bonus({ atk: 0.07, critResist: 0.01 }),
  },
  {
    id: 'treasure-fan',
    kind: 'equipment',
    name: '乾坤扇',
    description: '一扇分乾坤，风起时敌招尽散。',
    art: 'item/treasure-fan',
    grade: 'immortal',
    stackable: false,
    slot: 'treasure',
    requiredStage: 14,
    sellPrice: 1800,
    buyPrice: 4800,
    flat: bonus({ atk: 40, spd: 3 }),
    percent: bonus({ atk: 0.06, crit: 0.012, spd: 0.03 }),
  },
  {
    id: 'treasure-seal',
    kind: 'equipment',
    name: '山河印',
    description: '一印压山河，元婴以上修士方能驱使。',
    art: 'item/treasure-seal',
    grade: 'saint',
    stackable: false,
    slot: 'treasure',
    requiredStage: 22,
    sellPrice: 6000,
    buyPrice: 16000,
    flat: bonus({ atk: 120, def: 40 }),
    percent: bonus({ atk: 0.06, def: 0.02 }),
  },

  // ------------------------------------------------------------------ 法衣 robe
  {
    id: 'robe-linen',
    kind: 'equipment',
    name: '布衣',
    description: '粗麻所制，聊胜于无。',
    art: 'item/robe-linen',
    grade: 'mortal',
    stackable: false,
    slot: 'robe',
    requiredStage: 0,
    sellPrice: 30,
    buyPrice: 80,
    flat: bonus({ hp: 40, def: 4 }),
    percent: bonus({ hp: 0.06, def: 0.06 }),
  },
  {
    id: 'robe-daoist',
    kind: 'equipment',
    name: '道袍',
    description: '青云宗制式道袍，织有护体符纹。',
    art: 'item/robe-daoist',
    grade: 'spirit',
    stackable: false,
    slot: 'robe',
    requiredStage: 6,
    sellPrice: 320,
    buyPrice: 900,
    flat: bonus({ hp: 160, def: 12 }),
    percent: bonus({ hp: 0.06, def: 0.05, critResist: 0.01 }),
  },
  {
    id: 'robe-cloud',
    kind: 'equipment',
    name: '流云法衣',
    description: '云纹丝织就，行动如云，飘忽难中。',
    art: 'item/robe-cloud',
    grade: 'immortal',
    stackable: false,
    slot: 'robe',
    requiredStage: 14,
    sellPrice: 1600,
    buyPrice: 4200,
    flat: bonus({ hp: 520, def: 34 }),
    percent: bonus({ hp: 0.05, def: 0.05, eva: 0.012 }),
  },
  {
    id: 'robe-golden',
    kind: 'equipment',
    name: '金霞仙衣',
    description: '金霞蔽体，寻常法术难伤分毫。',
    art: 'item/robe-golden',
    grade: 'saint',
    stackable: false,
    slot: 'robe',
    requiredStage: 22,
    sellPrice: 5400,
    buyPrice: 14000,
    flat: bonus({ hp: 1600, def: 110 }),
    percent: bonus({ hp: 0.05, def: 0.05, critResist: 0.012 }),
  },

  // ------------------------------------------------------------ 饰品 accessory
  {
    id: 'acc-jade-pendant',
    kind: 'equipment',
    name: '玉佩',
    description: '温养神魂的灵玉小佩。',
    art: 'item/acc-jade-pendant',
    grade: 'mortal',
    stackable: false,
    slot: 'accessory',
    requiredStage: 0,
    sellPrice: 45,
    buyPrice: 120,
    flat: bonus({ hp: 20, spd: 1 }),
    percent: bonus({ spd: 0.04, acc: 0.008 }),
  },
  {
    id: 'acc-prayer-beads',
    kind: 'equipment',
    name: '菩提珠',
    description: '古刹遗珠，静心凝神，抗暴之效尤佳。',
    art: 'item/acc-prayer-beads',
    grade: 'spirit',
    stackable: false,
    slot: 'accessory',
    requiredStage: 8,
    sellPrice: 380,
    buyPrice: 1000,
    flat: bonus({ hp: 120, def: 8 }),
    percent: bonus({ critResist: 0.018, hp: 0.04 }),
  },
  {
    id: 'acc-talisman',
    kind: 'equipment',
    name: '护身符',
    description: '百草仙翁亲绘的护身符箓，闪避与命中兼顾。',
    art: 'item/acc-talisman',
    grade: 'immortal',
    stackable: false,
    slot: 'accessory',
    requiredStage: 16,
    sellPrice: 1900,
    buyPrice: 5000,
    flat: bonus({ hp: 400, spd: 4 }),
    percent: bonus({ eva: 0.015, acc: 0.015, spd: 0.04 }),
  },

  // ------------------------------------------------------------------- 灵宠 pet
  {
    id: 'pet-crane',
    kind: 'equipment',
    name: '仙鹤',
    description: '青云山中的白鹤灵禽，助主人身法轻灵。',
    art: 'item/pet-crane',
    grade: 'spirit',
    stackable: false,
    slot: 'pet',
    requiredStage: 4,
    sellPrice: 300,
    buyPrice: 850,
    flat: bonus({ spd: 3, hp: 80 }),
    percent: bonus({ spd: 0.06, eva: 0.01 }),
  },
  {
    id: 'pet-fox',
    kind: 'equipment',
    name: '灵狐',
    description: '九尾之属的幼裔，狡黠灵动，善觅生机。',
    art: 'item/pet-fox',
    grade: 'immortal',
    stackable: false,
    slot: 'pet',
    requiredStage: 12,
    sellPrice: 1500,
    buyPrice: 4000,
    flat: bonus({ atk: 26, spd: 3 }),
    percent: bonus({ crit: 0.02, atk: 0.05 }),
  },
  {
    id: 'pet-turtle',
    kind: 'equipment',
    name: '玄龟',
    description: '负山而行的玄龟，甲厚如岳，护主无虞。',
    art: 'item/pet-turtle',
    grade: 'saint',
    stackable: false,
    slot: 'pet',
    requiredStage: 20,
    sellPrice: 5200,
    buyPrice: 13500,
    flat: bonus({ hp: 1200, def: 90 }),
    percent: bonus({ hp: 0.06, def: 0.04 }),
  },
];

const RAW: Item[] = [...PILLS, ...MATERIALS, ...EQUIPMENT];

export const ITEMS: readonly Item[] = RAW.map((i) => ItemSchema.parse(i));
export const ITEM_BY_ID: ReadonlyMap<string, Item> = indexById(ITEMS);
export const ITEM_IDS: readonly string[] = ITEMS.map((i) => i.id);

export const PILL_ITEMS: readonly PillItem[] = ITEMS.filter(
  (i): i is PillItem => i.kind === 'pill',
);
export const MATERIAL_ITEMS: readonly MaterialItem[] = ITEMS.filter(
  (i): i is MaterialItem => i.kind === 'material',
);
export const EQUIPMENT_ITEMS: readonly EquipmentItem[] = ITEMS.filter(
  (i): i is EquipmentItem => i.kind === 'equipment',
);

/** The 破境丹 consumed by breakthrough attempts. */
export const BREAKTHROUGH_PILL_ID = 'pill-breakthrough';

export function getItem(itemId: string): Item | undefined {
  return ITEM_BY_ID.get(itemId);
}

export function isEquipment(item: Item | undefined): item is EquipmentItem {
  return item?.kind === 'equipment';
}
